# Generated by Django 4.2.5 on 2023-09-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='published_date',
            new_name='published_at',
        ),
    ]
