# Generated by Django 4.2.5 on 2023-09-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_rename_published_date_video_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='published_date',
            new_name='published_at',
        ),
    ]
